import { Category, Product } from './types';

export const CATEGORIES: Category[] = [
  {
    id: 'living-room',
    name: 'Living Room',
    image: 'https://picsum.photos/seed/living/400/400',
    color: 'bg-brand-pink',
  },
  {
    id: 'bedroom',
    name: 'Bedroom',
    image: 'https://picsum.photos/seed/bedroom/400/400',
    color: 'bg-brand-yellow',
  },
  {
    id: 'office',
    name: 'Office',
    image: 'https://picsum.photos/seed/office/400/400',
    color: 'bg-brand-cyan',
  },
  {
    id: 'dining',
    name: 'Dining',
    image: 'https://picsum.photos/seed/dining/400/400',
    color: 'bg-brand-purple',
  },
  {
    id: 'decor',
    name: 'Decor',
    image: 'https://picsum.photos/seed/decor/400/400',
    color: 'bg-brand-green',
  },
  {
    id: 'outdoor',
    name: 'Outdoor',
    image: 'https://picsum.photos/seed/outdoor/400/400',
    color: 'bg-orange-400',
  },
];

export const PRODUCTS: Product[] = [
  {
    id: '1',
    name: 'The Main Character Couch',
    price: 899,
    category: 'living-room',
    image: 'https://picsum.photos/seed/couch1/600/600',
    description: 'A velvet masterpiece that screams "I have arrived." Perfect for your next TikTok background.',
    tags: ['Velvet', 'Pink', 'Curvy'],
    isBestseller: true,
  },
  {
    id: '2',
    name: 'No Cap Coffee Table',
    price: 249,
    category: 'living-room',
    image: 'https://picsum.photos/seed/table1/600/600',
    description: 'Transparent acrylic with neon edges. It’s giving futuristic vibes.',
    tags: ['Acrylic', 'Neon', 'Modern'],
    isNew: true,
  },
  {
    id: '3',
    name: 'Main Quest Desk',
    price: 450,
    category: 'office',
    image: 'https://picsum.photos/seed/desk1/600/600',
    description: 'Ergonomic but make it fashion. Built-in RGB lighting for maximum focus.',
    tags: ['RGB', 'Gaming', 'Ergonomic'],
  },
  {
    id: '4',
    name: 'Slumber Party Bed',
    price: 1200,
    category: 'bedroom',
    image: 'https://picsum.photos/seed/bed1/600/600',
    description: 'Cloud-like comfort with a headboard that doubles as a mood light.',
    tags: ['Cloud', 'Soft', 'LED'],
    isBestseller: true,
  },
  {
    id: '5',
    name: 'Vibe Check Mirror',
    price: 150,
    category: 'decor',
    image: 'https://picsum.photos/seed/mirror1/600/600',
    description: 'Wavy frame that makes every outfit look like a 10/10.',
    tags: ['Wavy', 'Selfie', 'Aesthetic'],
    isNew: true,
  },
  {
    id: '6',
    name: 'Main Character Chair',
    price: 320,
    category: 'office',
    image: 'https://picsum.photos/seed/chair1/600/600',
    description: 'A swivel chair that actually looks good in your room.',
    tags: ['Swivel', 'Yellow', 'Retro'],
  },
  {
    id: '7',
    name: 'Midnight Snack Cabinet',
    price: 580,
    category: 'dining',
    image: 'https://picsum.photos/seed/cabinet1/600/600',
    description: 'Store your snacks in style. Checkerboard pattern for that retro-modern feel.',
    tags: ['Checkerboard', 'Storage', 'Retro'],
  },
  {
    id: '8',
    name: 'Touch Grass Patio Set',
    price: 750,
    category: 'outdoor',
    image: 'https://picsum.photos/seed/outdoor1/600/600',
    description: 'Weatherproof and aesthetic. Perfect for your balcony garden.',
    tags: ['Outdoor', 'Green', 'Minimalist'],
  },
];
